### ISSUE TITLE
patch makes migration to dexterity impossible

### ISSUE THREAD

**Issue by skillfully** [collective/collective.base64imagepatch#5]
Using ...
Plone: v4.3.4
Zope: v2.13.23
Python: v2.7.13

with installed
- collective.base64imagepatch v0.12
- plone.app.contenttypes v1.1.6
- plone.app.dexterity v2.0.11
- ... and some other add-ons

starting migration via @@atct_migrator view results in following traceback

```
2020-01-21T09:40:54 ERROR ATCT.migration Failed migration for object /ub2_213/shared (Folder -> Folder)
Traceback (most recent call last):
  File "/var/tmp/buildout/eggs/cp27mu/Products.contentmigration-2.1.9-py2.7.egg/Products/contentmigration/basemigrator/walker.py", line 192, in migrate
    migrator.migrate()
  File "/var/tmp/buildout/eggs/cp27mu/Products.contentmigration-2.1.9-py2.7.egg/Products/contentmigration/basemigrator/migrator.py", line 220, in migrate
    method()
  File "/var/tmp/buildout/eggs/cp27mu/Products.contentmigration-2.1.9-py2.7.egg/Products/contentmigration/basemigrator/migrator.py", line 577, in migrate_children
    self.new._setObject(id, obj, set_owner=0)
  File "/var/tmp/buildout/eggs/cp27mu/Products.BTreeFolder2-2.13.3-py2.7.egg/Products/BTreeFolder2/BTreeFolder2.py", line 455, in _setObject
    notify(ObjectAddedEvent(ob, self, id))
  File "/var/tmp/buildout/eggs/cp27mu/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/tmp/buildout/eggs/cp27mu/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 32, in objectEventNotify
    zope.component.subscribers((event.object, event), None)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/tmp/buildout/eggs/cp27mu/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/var/tmp/buildout/eggs/cp27mu/Zope2-2.13.23-py2.7.egg/OFS/subscribers.py", line 113, in dispatchObjectMovedEvent
    dispatchToSublocations(ob, event)
  File "/var/tmp/buildout/eggs/cp27mu/zope.container-3.11.2-py2.7-linux-x86_64.egg/zope/container/contained.py", line 153, in dispatchToSublocations
    for ignored in zope.component.subscribers((sub, event), None):
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/tmp/buildout/eggs/cp27mu/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/var/tmp/buildout/eggs/cp27mu/Zope2-2.13.23-py2.7.egg/OFS/subscribers.py", line 113, in dispatchObjectMovedEvent
    dispatchToSublocations(ob, event)
  File "/var/tmp/buildout/eggs/cp27mu/zope.container-3.11.2-py2.7-linux-x86_64.egg/zope/container/contained.py", line 153, in dispatchToSublocations
    for ignored in zope.component.subscribers((sub, event), None):
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/tmp/buildout/eggs/cp27mu/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/var/tmp/buildout/eggs/cp27mu/Zope2-2.13.23-py2.7.egg/OFS/subscribers.py", line 113, in dispatchObjectMovedEvent
    dispatchToSublocations(ob, event)
  File "/var/tmp/buildout/eggs/cp27mu/zope.container-3.11.2-py2.7-linux-x86_64.egg/zope/container/contained.py", line 153, in dispatchToSublocations
    for ignored in zope.component.subscribers((sub, event), None):
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/tmp/buildout/eggs/cp27mu/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/var/tmp/buildout/eggs/cp27mu/collective.base64imagepatch-0.12-py2.7.egg/collective/base64imagepatch/subscribers.py", line 10, in patch_base64_images_on_create
    patch_object(context)
  File "/var/tmp/buildout/eggs/cp27mu/collective.base64imagepatch-0.12-py2.7.egg/collective/base64imagepatch/patch.py", line 54, in patch_object
    new_content = patch(container, obj, name, field_content)
  File "/var/tmp/buildout/eggs/cp27mu/collective.base64imagepatch-0.12-py2.7.egg/collective/base64imagepatch/patch.py", line 191, in patch
    base64.b64decode(img_data))
  File "/var/tmp/buildout/eggs/cp27mu/collective.base64imagepatch-0.12-py2.7.egg/collective/base64imagepatch/patch.py", line 128, in createImage
    image=image_data
  File "/var/tmp/buildout/eggs/cp27mu/Products.ATContentTypes-2.1.12-py2.7.egg/Products/ATContentTypes/lib/constraintypes.py", line 277, in invokeFactory
    RESPONSE=None, *args, **kw)
  File "/var/tmp/buildout/eggs/cp27mu/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/PortalFolder.py", line 290, in invokeFactory
    raise ValueError('Disallowed subobject type: %s' % type_name)
ValueError: Disallowed subobject type: Image
------
2020-01-21T09:40:54 ERROR ATCT.migration FATAL: Migration has failed, aborting transaction!
------
2020-01-21T09:40:55 ERROR Zope.SiteErrorLog 1579596055.30.836542635834 http://localhost:12345/ub2_213/@@atct_migrator
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module z3c.form.form, line 213, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.app.contenttypes.migration.browser, line 384, in handle_migrate
  Module plone.app.contenttypes.migration.browser, line 219, in __call__
  Module plone.app.contenttypes.migration.migration, line 339, in migrate_folders
  Module plone.app.contenttypes.migration.migration, line 51, in migrate
  Module Products.contentmigration.basemigrator.walker, line 144, in go
  Module Products.contentmigration.basemigrator.walker, line 223, in migrate
MigrationError: MigrationError for obj at /ub2_213/shared (Folder -> Folder):
Traceback (most recent call last):
  File "/var/tmp/buildout/eggs/cp27mu/Products.contentmigration-2.1.9-py2.7.egg/Products/contentmigration/basemigrator/walker.py", line 192, in migrate
    migrator.migrate()
  File "/var/tmp/buildout/eggs/cp27mu/Products.contentmigration-2.1.9-py2.7.egg/Products/contentmigration/basemigrator/migrator.py", line 220, in migrate
    method()
  File "/var/tmp/buildout/eggs/cp27mu/Products.contentmigration-2.1.9-py2.7.egg/Products/contentmigration/basemigrator/migrator.py", line 577, in migrate_children
    self.new._setObject(id, obj, set_owner=0)
  File "/var/tmp/buildout/eggs/cp27mu/Products.BTreeFolder2-2.13.3-py2.7.egg/Products/BTreeFolder2/BTreeFolder2.py", line 455, in _setObject
    notify(ObjectAddedEvent(ob, self, id))
  File "/var/tmp/buildout/eggs/cp27mu/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/tmp/buildout/eggs/cp27mu/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 32, in objectEventNotify
    zope.component.subscribers((event.object, event), None)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/tmp/buildout/eggs/cp27mu/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/var/tmp/buildout/eggs/cp27mu/Zope2-2.13.23-py2.7.egg/OFS/subscribers.py", line 113, in dispatchObjectMovedEvent
    dispatchToSublocations(ob, event)
  File "/var/tmp/buildout/eggs/cp27mu/zope.container-3.11.2-py2.7-linux-x86_64.egg/zope/container/contained.py", line 153, in dispatchToSublocations
    for ignored in zope.component.subscribers((sub, event), None):
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/tmp/buildout/eggs/cp27mu/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/var/tmp/buildout/eggs/cp27mu/Zope2-2.13.23-py2.7.egg/OFS/subscribers.py", line 113, in dispatchObjectMovedEvent
    dispatchToSublocations(ob, event)
  File "/var/tmp/buildout/eggs/cp27mu/zope.container-3.11.2-py2.7-linux-x86_64.egg/zope/container/contained.py", line 153, in dispatchToSublocations
    for ignored in zope.component.subscribers((sub, event), None):
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/tmp/buildout/eggs/cp27mu/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/var/tmp/buildout/eggs/cp27mu/Zope2-2.13.23-py2.7.egg/OFS/subscribers.py", line 113, in dispatchObjectMovedEvent
    dispatchToSublocations(ob, event)
  File "/var/tmp/buildout/eggs/cp27mu/zope.container-3.11.2-py2.7-linux-x86_64.egg/zope/container/contained.py", line 153, in dispatchToSublocations
    for ignored in zope.component.subscribers((sub, event), None):
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/var/tmp/buildout/eggs/cp27mu/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/tmp/buildout/eggs/cp27mu/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/var/tmp/buildout/eggs/cp27mu/collective.base64imagepatch-0.12-py2.7.egg/collective/base64imagepatch/subscribers.py", line 10, in patch_base64_images_on_create
    patch_object(context)
  File "/var/tmp/buildout/eggs/cp27mu/collective.base64imagepatch-0.12-py2.7.egg/collective/base64imagepatch/patch.py", line 54, in patch_object
    new_content = patch(container, obj, name, field_content)
  File "/var/tmp/buildout/eggs/cp27mu/collective.base64imagepatch-0.12-py2.7.egg/collective/base64imagepatch/patch.py", line 191, in patch
    base64.b64decode(img_data))
  File "/var/tmp/buildout/eggs/cp27mu/collective.base64imagepatch-0.12-py2.7.egg/collective/base64imagepatch/patch.py", line 128, in createImage
    image=image_data
  File "/var/tmp/buildout/eggs/cp27mu/Products.ATContentTypes-2.1.12-py2.7.egg/Products/ATContentTypes/lib/constraintypes.py", line 277, in invokeFactory
    RESPONSE=None, *args, **kw)
  File "/var/tmp/buildout/eggs/cp27mu/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/PortalFolder.py", line 290, in invokeFactory
    raise ValueError('Disallowed subobject type: %s' % type_name)
ValueError: Disallowed subobject type: Image
```

The current work-around is to remove collective.base64imagepatch from buildout while migration.

**Comment by MrTango** [comment]
this extension does one thing, it takes out the base64encodes imges from the fulltext and creates image objects in Plone instead. If it does this only in the migration, then you probably still have some RichText fields with base64encoded images. I would try to save them again to have the extension doing it's job before starting the migration. 
The error it self just says that you are trying to put objects into other object where they are not allowed, this con be changed too in the FTI setting of that containerish object.

**Comment by loechel** [comment]
You could run the patch_all upfront before migration:

``http://localhost:8080/Plone/patch_all``

Then look if everything work as expected, and if not, you have a self written foldish-contenttype that do not allow Images as subelements. That needs either some fixes in this package or your content-type.

Migaration from Archetypes to Dexertity could and should be applied afterwards.

**Comment by skillfully** [comment]
Thanks Alexander for the hint, the `patch_all` view makes it possible to migrate
